UniResearch/ViewModels/SearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UniResearch.Models;

namespace UniResearch.ViewModels
{
    public class SearchViewModel
    {
        public string SearchKey { get; set; }
        public IEnumerable<Paper> Result { get; set; }
    }
}

UniResearch/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UniResearch.Models;
using UniResearch.ViewModels;

namespace UniResearch.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentRepository _commentRepository;
        private readonly IPaperRepository _paperRepository;
        private readonly IProfileRepository _profileRepository;

        public CommentController(ICommentRepository commentRepository, IPaperRepository paperRepository, IProfileRepository profileRepository)
        {
            _commentRepository = commentRepository;
            _paperRepository = paperRepository;
            _profileRepository = profileRepository;
        }

        [HttpGet]
        public IActionResult PaperComments(int paperId)
        {
            var comments = _commentRepository.GetPaperComments(paperId);
            comments = comments.Reverse();
            var paper = _paperRepository.GetPaper(paperId);
            string loggedProfileName;
            CommentViewModel model = new CommentViewModel();
            try
            {
                loggedProfileName = _profileRepository.GetProfileName(User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value);

                model.ApplicationUserId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value;
                model.CommentProfileName = loggedProfileName;
                model.Comments = comments;
                model.Paper = paper;
            }
            catch (Exception ex)
            {
                loggedProfileName = null;

                model.ApplicationUserId = null;
                model.CommentProfileName = loggedProfileName;
                model.Comments = comments;
                model.Paper = paper;
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult PaperComments(CommentViewModel commentViewModel)
        {
            //if (ModelState.IsValid)
            //{
            if (commentViewModel.CommentText == null)
                return RedirectToAction("PaperComments", new { paperId = commentViewModel.Paper.Id });

            Comment comment = new Comment
            {
                PaperId = commentViewModel.Paper.Id,
                ApplicationUserId = commentViewModel.ApplicationUserId,
                CommentText = commentViewModel.CommentText
            };
            _commentRepository.AddComment(comment);
            //}
            return RedirectToAction("PaperComments", new { paperId = commentViewModel.Paper.Id });
        }

        public IActionResult DeleteComment(int commentId, int papId)
        {
            _commentRepository.DeleteComment(commentId);
            return RedirectToAction("PaperComments", new { paperId = papId });
        }
    }
}

UniResearch/Controllers/PaperController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using UniResearch.Models;
using UniResearch.ViewModels;

namespace UniResearch.Controllers
{
    public class PaperController : Controller
    {
        private readonly IPaperRepository _paperRepository;
        private readonly IHostingEnvironment _hostingEnvironment;

        public PaperController(IPaperRepository paperRepository, IHostingEnvironment hostingEnvironment)
        {
            _paperRepository = paperRepository;
            _hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        public IActionResult AddPaper(string userId)
        {
            AddPaperViewModel model = new AddPaperViewModel { ProfileUserId = userId };
            return View(model);
        }

        [HttpPost]
        public IActionResult AddPaper(AddPaperViewModel model)
        {
            //if (ModelState.IsValid)
            //{
            //if (model.Paper == null || model.PaperName == null)
            //    return RedirectToAction("Profile", "Profile", new { userId = model.ProfileUserId });
            Paper paper = new Paper();
            paper.PaperName = model.PaperName;
            paper.PaperFilePath = FileUpload(model.Paper);
            paper.UsersPapers.Add(new UserPaper { ApplicationUserId = model.ProfileUserId, PaperId = model.Id });
            _paperRepository.AddPaper(paper);
            //}
            return RedirectToAction("Profile", "Profile", new { userId = model.ProfileUserId });
        }

        private string FileUpload(IFormFile File)
        {
            string uniqueFileName = null;

            // If the Photo property on the incoming model object is not null, then the user
            // has selected an image to upload.
            if (File != null)
            {
                // The image must be uploaded to the images folder in wwwroot
                // To get the path of the wwwroot folder we are using the inject
                // HostingEnvironment service provided by ASP.NET Core
                string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "papers");
                // To make sure the file name is unique we are appending a new
                // GUID value and and an underscore to the file name
                uniqueFileName = Guid.NewGuid().ToString() + "_" + File.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                // Use CopyTo() method provided by IFormFile interface to
                // copy the file to wwwroot/images folder
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    File.CopyTo(fileStream);
                }
                //File.CopyTo(new FileStream(filePath, FileMode.Create));
            }
            return uniqueFileName;
        }

        public async Task<IActionResult> Download(string filename)
        {
            //if (filename == null)
            //    return Content("filename not present");

            var path = Path.Combine(_hostingEnvironment.WebRootPath, "papers", filename);

            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, GetContentType(path), Path.GetFileName(path));
        }

        private string GetContentType(string path)
        {
            var types = GetMimeTypes();
            var ext = Path.GetExtension(path).ToLowerInvariant();
            return types[ext];
        }

        private Dictionary<string, string> GetMimeTypes()
        {
            return new Dictionary<string, string>
            {
                {".txt", "text/plain"},
                {".pdf", "application/pdf"},
                {".doc", "application/vnd.ms-word"},
                {".docx", "application/vnd.ms-word"},
                {".xls", "application/vnd.ms-excel"},
                {".xlsx", "application/vnd.openxmlformats" +
                "officedocument.spreadsheetml.sheet"},
                {".png", "image/png"},
                {".jpg", "image/jpeg"},
                {".jpeg", "image/jpeg"},
                {".gif", "image/gif"},
                {".csv", "text/csv"}
            };
        }

        public IActionResult Delete(int paperId)
        {
            var paperFilePath = _paperRepository.GetPaper(paperId).PaperFilePath;
            _paperRepository.DeletePaper(paperId, User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value);
            //if (paperFilePath != null)
            //{
            //    string filePath = Path.Combine(_hostingEnvironment.WebRootPath, "papers", paperFilePath);
            //    System.IO.File.Delete(filePath);
            //}
            return RedirectToAction("Profile", "Profile", new { userId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value });
        }
    }
}

UniResearch/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UniResearch.Models;
using UniResearch.ViewModels;

namespace UniResearch.Controllers
{
    public class SearchController : Controller
    {
        private readonly ISearchRepository _searchRepository;

        public SearchController(ISearchRepository searchRepository)
        {
            _searchRepository = searchRepository;
        }

        [HttpGet]
        public IActionResult SearchByPaperName(string searchKey)
        {
            SearchViewModel result = _searchRepository.SearchByPaperName(searchKey);
            return View("PaperSearch", result);
        }

        [HttpPost]
        public IActionResult SearchByPaperName(SearchViewModel searchViewModel)
        {
            return RedirectToAction("SearchByPaperName", new { searchKey = searchViewModel.SearchKey });
            //SearchViewModel result = _searchRepository.SearchByPaperName(searchViewModel.SearchKey);
            //return View("PaperSearch", result);
        }
    }
}

UniResearch/Views/Search/PaperSearch.cshtml
@inject ApplicationDbContext context

@model SearchViewModel
@{
    ViewData["Title"] = "PaperSearch";
}

<form method="post">
    <div class="container">
        <!---------------------------------------------------Search---------------------------------------------------->
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-6">
                <div class="mb-2">
                    <input asp-for="SearchKey" class="form-control form-control-lg" id="searchKey" value="@Model.SearchKey">
                </div>
            </div>
            <div class="col-md-2">
                <div class="mb-4">
                    <button type="submit" class="btn btn-block btn-lg btn-primary">Search!</button>
                    @*<a asp-controller="Search" asp-action="SearchByPaperName" asp-route-searchKey="@Model.SearchKey" class="btn btn-block btn-lg btn-primary">Search!</a>*@
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>

        <!---------------------------------------------------Results---------------------------------------------------->
        @foreach (var paper in Model.Result)
        {
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">

                    <div class="mb-4">
                        <div class="card border-0 shadow">
                            <div class="card-body">

                                <div class="row">
                                    <div class="col-md-12">
                                        <h5 class="card-title mb-0">
                                            <a asp-controller="Comment" asp-action="PaperComments" asp-route-paperId="@paper.Id">@paper.PaperName</a>
                                        </h5>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        @foreach (var user in paper.UsersPapers)
                                        {
                                            var userProfileName = context.ApplicationUsers.FirstOrDefault(u => u.Id == user.ApplicationUserId).ProfileName;

                                            <div class="card-text text-black-50">
                                                <a asp-controller="Profile" asp-action="Profile" asp-route-userId="@user.ApplicationUserId">@userProfileName</a>
                                            </div>
                                        }
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-8"></div>
                                    <div class="col-md-4">
                                        <a asp-controller="Paper" asp-action="Download" asp-route-filename="@paper.PaperFilePath" class="btn mb-2 btn-block btn-md btn-primary">Download</a>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

                </div>
                <div class="col-md-2"></div>
            </div>
        }


    </div>
</form>